### PR TITLE
Replace the static html app with a Dash app

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
This PR is a like-for-like replacement for the old Cage Porosity website app using Dash.

Extended features mentioned in #7 and generalisable Dash objects #10 are yet to be implemented.
Screenshot 2022-04-29 at 13 09 30

### CODE REVIEW

**Review by dandavies99 — CHANGES_REQUESTED** [review]
This looks great, very neat. I wonder whether at this stage it would be good to add a few comments in app.py around the non-obvious Dash stuff, e.g. the callback decorators, "children" and `MATCH`? 

Other than that I think it's good to go.

**Comment by AdrianDAlessandro** [comment]
> This looks great, very neat. I wonder whether at this stage it would be good to add a few comments in app.py around the non-obvious Dash stuff, e.g. the callback decorators, "children" and `MATCH`?

I added in docstrings for the callbacks with a brief explanation and a link for the `MATCH` stuff. The rest is fairly basic standard Dash (plus bootstrap, which simplifies it). You mentioned "children" that's the parameter for any `html` or `dbc` class that defines what is inside it (Button, Row, Div, Label, Img, etc)

**Comment by AdrianDAlessandro** [comment]
@cc-a Can I get you to double check the Docker setup (mainly the last commit)? I also fixed that relative vs absolute import issue by running the app as a module instead of the file directly (i.e. `python -m website.app`). This is done in the `docker-compose.yml`, so you can have the container running in debug mode locally but should work in the production server.

**Review by dandavies99 — APPROVED** [review]
Looks good to me. The environment seems to take longer to build but that's probably just down to the necessary tweaks. Not really a problem as it only needs to happen once. 

I think the changes to the `Dockerfile` and `docker-compose.yml` are fine. We will just have to update the `docker-compose.yml` on the production machine accordingly and troubleshoot if we hit any snags.

**Comment by dandavies99** [comment]
Just double checking @AdrianDAlessandro - because it's been a while - that this is good to merge?

**Comment by AdrianDAlessandro** [comment]
> Just double checking @AdrianDAlessandro - because it's been a while - that this is good to merge?

Yes! This is good to go! Would like to get it working on the production machine.

**Pull request merged**
