### PR TITLE
Create the JSME drawer components

### LINKED ISSUE #10: General Dash functions
Create generic Dash functions (possibly in separate repo) to be imported and used in every model. e.g. for file upload.

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
This PR includes the jsme object from `dash-bio` that allows chemical structure to be drawn in the browser. It also allows for a `.mol` file to be uploaded and the editable structure to appear in the jsme.

This requires removing restrictions on the package versions. I am treating this PR as the step that turns this repo from the Cage Porosity App to a template.

Close #10

### CODE REVIEW

**Review by dandavies99 — COMMENTED** [review]
Looks good in principle. I like the layout of having a top level `app_list.json`.

Yeh, the failing test is due to a different version of scikit-learn presumably being required and the model having been moved to a different module. 

I think we need to stop and consider exactly how we want to proceed: We need to transition into having a template, but also having the working version of the specific Cage Porosity app that uses the template. This will also be true for the data browsing example. Essentially we have two examples based on one template and need to lay that out on GitHub in the best way.

**Comment by AdrianDAlessandro** [comment]
@dandavies99 I had the same thought as you and just split the navbar-related stuff into a separate PR so that the Cage Porosity app can be created from this and use it before we make this template more generalised by merging this PR.

**Comment by dandavies99** [comment]
@AdrianDAlessandro is this ready to merge now or still in draft?

**Review by dandavies99 — APPROVED** [review]
This all looks good. I guess the point is that this template is not intended to run, so will not work if run locally. But rather to demonstrate the different components that can be included. I'll add a note to the docs to see the cage-porosity-webapp for a working example, and we'll have another data browsing example at some point too.

**Comment by AdrianDAlessandro** [comment]
> This all looks good. I guess the point is that this template is not intended to run, so will not work if run locally. But rather to demonstrate the different components that can be included. I'll add a note to the docs to see the cage-porosity-webapp for a working example, and we'll have another data browsing example at some point too.

It does run locally! At least the web app does. You'll just have to update your conda environment / create a new one. Or create a new docker image. But the model doesn't run (the model files have been removed after all!)

**Comment by dandavies99** [comment]
Yeh I know - I've run it locally. I only said it's not _intended_ to run locally and will not work if you do so. By "work" I meant do something useful like allow you to use a model, so I wouldn't call it a working example. I suppose there is some value in being able to preview the components though.

**Pull request merged**
